-- MySQL Script generated by MySQL Workbench
-- Sat Jul 18 15:00:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DocuHub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DocuHub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DocuHub` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `DocuHub` ;

-- -----------------------------------------------------
-- Table `DocuHub`.`RingBinders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DocuHub`.`RingBinders` ;

CREATE TABLE IF NOT EXISTS `DocuHub`.`RingBinders` (
  `RingBinderId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `GUID` VARCHAR(32) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` TINYTEXT NULL,
  `Pinned` BINARY(1) NOT NULL DEFAULT 0,
  `Color` VARCHAR(6) NULL,
  PRIMARY KEY (`RingBinderId`),
  UNIQUE INDEX `GUID_UNIQUE` (`GUID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
CHECKSUM = 1;


-- -----------------------------------------------------
-- Table `DocuHub`.`Pages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DocuHub`.`Pages` ;

CREATE TABLE IF NOT EXISTS `DocuHub`.`Pages` (
  `PageId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `GUID` VARCHAR(32) NOT NULL,
  `RingBinderId` INT UNSIGNED NOT NULL,
  `Parent` BIGINT UNSIGNED NOT NULL,
  `PageType` TINYINT NOT NULL DEFAULT 0 COMMENT '0 - dokument MD\n1 - dokument PDF',
  `Title` VARCHAR(1024) NOT NULL DEFAULT 'New Page',
  `Body` LONGTEXT NOT NULL COMMENT 'Treść dokumentu md bądź ścieżka do zasobu',
  PRIMARY KEY (`PageId`),
  UNIQUE INDEX `GUID_UNIQUE` (`GUID` ASC) VISIBLE,
  INDEX `FK_Pages_RingBinderId_idx` (`RingBinderId` ASC) VISIBLE,
  INDEX `FK_Pages_Parent_idx` (`Parent` ASC) VISIBLE,
  CONSTRAINT `FK_Pages_RingBinderId`
    FOREIGN KEY (`RingBinderId`)
    REFERENCES `DocuHub`.`RingBinders` (`RingBinderId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Pages_Parent`
    FOREIGN KEY (`Parent`)
    REFERENCES `DocuHub`.`Pages` (`PageId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
